### ISSUE TITLE
Add placeholder strategies

### ISSUE THREAD

**Issue by tleperou** [gioboa/qwik-image#5]
✌️ 

Implement strategies to support a placeholder while loading the source of the image.

# Options

## minified image 

- Lower drastically the time to provide feedback to user
- Requires another image source

## background colour

- Instantly provide feedback to user
- Requires a colour to be provided
- The dominant colour could be retrieve at build time, but does it really worth it .. seems excessively heavy

## blur

- Quiet similar to minified image

## loader

- show a loader until the source is loaded

## empty

An empty placeholder

# References

- https://nextjs.org/docs/api-reference/next/image#placeholder

**Comment by gioboa** [comment]
there are a lot of possibilities but I think that the background colour way is a good enough for the first version of this component.
